### PR TITLE
Reduce size of docker image

### PR DESCRIPTION
**Pull request by pan3793**
**Changelog category (leave one)**

- Other

**Changelog entry (Details of this change)**

Reduce size of docker image by leveraging command `ADD`

**Affected version**

`latest version`

### CODE REVIEW

**Review by qianmoQ — COMMENTED** [review]
Message that will be displayed on users' first pull request

**Comment by pan3793** [comment]
Sorry, I can not pass the test locally, it failed w/ 

```
=> ERROR [internal] load metadata for docker.io/library/java:8
```

If you don't mind, I would recommend switching to `eclipse-temurin:8-jdk-focal`, it was adopted by a bunch of apache projects like Apache Spark.

**Comment by qianmoQ** [comment]
> Sorry, I can not pass the test locally, it failed w/
> 
> ```
> => ERROR [internal] load metadata for docker.io/library/java:8
> ```
> 
> If you don't mind, I would recommend switching to `eclipse-temurin:8-jdk-focal`, it was adopted by a bunch of apache projects like Apache Spark.

This is a good suggestion. You can modify it and submit it again

**Comment by pan3793** [comment]
updated

**Comment by pan3793** [comment]
This is an interesting project, and I'm glad to see it supports Apache Kyuubi (incubating) officially, do you want to add the Datacap integration guide to Kyuubi docs[1]? The entry point of the codebase at [2]. I think both projects will benefit from it.

BTW, is EdurtIO a commercialized organization or a community organization? If the latter, are there criteria to join?

[1] https://kyuubi.readthedocs.io/en/latest/client/index.html
[2] https://github.com/apache/incubator-kyuubi/tree/master/docs/client

**Comment by qianmoQ** [comment]
> This is an interesting project, and I'm glad to see it supports Apache Kyuubi (incubating) officially, do you want to add the Datacap integration guide to Kyuubi docs[1]? The entry point of the codebase at [2]. I think both projects will benefit from it.
> 
> BTW, is EdurtIO a commercialized organization or a community organization? If the latter, are there criteria to join?
> 
> [1] https://kyuubi.readthedocs.io/en/latest/client/index.html [2] https://github.com/apache/incubator-kyuubi/tree/master/docs/client

Open source community organization, feel free to join

**Comment by qianmoQ** [comment]
LGTM, thanks for your contribtue!

**Pull request merged**
